# Generated by Django 4.1.7 on 2023-04-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categiria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='categiria',
            new_name='categoria',
        ),
    ]
