# Generated by Django 4.1.7 on 2023-04-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_rename_categiria_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
