# Generated by Django 4.1.7 on 2023-04-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='public',
            new_name='publicada',
        ),
    ]
